---
- hosts: balancer
  tasks:
    - name: Instalação de pacotes básicos
      apt: name={{ item }} state=installed
      with_items:
        - build-essential
        - mutt
        - openssh-client
        - python-pip
        - python3-pip
      tags:
        - packages
    - name: Instalar nginx
      apt: name=nginx state=latest
      become: yes
    - name: Iniciar nginx
      service:
          name: nginx
          state: started
      become: yes
    - name: copiar arquivo de configuração
      copy:
        src: ./files/config/dominio.conf
        dest: /etc/nginx/sites-available/dominio.conf
      become: yes
    - name: criar link simbolico para sites-enabled
      file:
        src: /etc/nginx/sites-available/dominio.conf
        dest: /etc/nginx/sites-enabled/default
        state: link
      become: yes
    - name: restart nginx
      service:
        name: nginx
        state: restarted
      become: yes
