---
- hosts: nodeapp
  vars:
    project_path: /var/www/nodejs
    ansible_user_id: root
  tasks:
    - name: Instalação nvm
      shell: 
        curl https://raw.githubusercontent.com/creationix/nvm/v0.33.11/install.sh | bash
        creates=/home/{{ ansible_user_id }}/.nvm/nvm.sh
    - name: instalação node LTS
      shell:
        /bin/bash -c "source ~/.nvm/nvm.sh && nvm install 10.14.0 && nvm alias default 10.14.0"
        creates=/home/{{ ansible_user_id }}/.nvm/alias
#    - name: Criação pasta para aplicações node
#      file:
#        path:/var/www/nodejs
#        mode=0755
#        recurse=yes
#        state=directory
