---
- hosts: nodeapp
  vars:
    project_path: /var/www/nodejs
    ansible_user: root
    version_nodeapp: 1.0.0
    nvm_node_version: 10.14.0
  tasks:
    - name: Instalação nvm
      shell: 
        curl https://raw.githubusercontent.com/creationix/nvm/v0.33.11/install.sh | bash
        creates=/home/{{ ansible_user }}/.nvm/nvm.sh
    - name: instalação node {{nvm_node_version}}
      shell:
        /bin/bash -c "source ~/.nvm/nvm.sh && nvm install {{nvm_node_version}} && nvm alias default {{nvm_node_version}}"
        creates=/home/{{ ansible_user }}/.nvm/alias
    - name: Criação pasta para aplicações node
      file: 
        path=/var/www/nodejs
        mode=0755
        recurse=yes
        state=directory
    - name: Copia projeto versão {{version_nodeapp}}
      copy: 
        src: ./deploy/app_v{{version_nodeapp}}.js
        dest: /var/www/nodejs
      become: yes
#Solução abaixo foi implementada pois o modulo npm do ansible não está funcional com a versão 6.4.1 que foi instalada juntamente com o node LTS através no nvm.
    - name: Instalação npm 3.5.2
      apt:
        name: npm
        state: installed
    - name: Instalação de dependências
      become: yes
      become_user: "{{ ansible_ssh_user }}"
      npm:
       name: express
       global: no
       path: /var/www/nodejs/app_v{{version_nodeapp}}.js    
       state: present
    - name:  Instalação pm2
      become: yes
      become_user: "{{ ansible_ssh_user }}"
      npm:
       name: pm2
       global: yes
       production: yes
       state: present
    - name: Link simbolico nodejs/node
      file:
        src: /usr/bin/nodejs
        dest: /usr/bin/node
        state: link
    - name: Iniciar aplicação com pm2
      become_user: root
      command: pm2 start {{project_path}}/app_v{{version_nodeapp}}.js/ -i max --watch
#    - name: Definição de variáveis
#      set_fact:
#        release_path: "{{ project_path }}/releases/{{ lookup('pipe','date +%Y%m%d%H%M%S') }}"
#        current_path: "{{ project_path }}/current"
#    - name: Recuperar pasta de lançamento atual
#      command: readlink -f current
#      register: current_release_path
#      ignore_errors: yes
#      args:
#        chdir: "{{ project_path }}"
#    - name: Create new folder
#      file:
#        dest={{ release_path }}
#        mode=0755
#        recurse=yes
#        state=directory
#    - name: Update symlink
#      file:
#        src={{ release_path }}
#        dest={{ current_path }}
#        state=link
#    - name: Remover versão antiga de aplicação no pm2
#      command: pm2 delete ws-node
#     ignore_errors: yes
